export const adImageMapping: Record<string, Record<string, string>> = {
  'Général': {
    default: 'http://bilingue31.free.fr/ElectroMenage_LaveLinge_OK.jpg',
    'Animaux': 'http://bilingue31.free.fr/general_Animaux2_OK.jpg',
    'Bricolage': 'http://bilingue31.free.fr/general_Bricolage_OK.jpg',
    'Divers': 'http://bilingue31.free.fr/general_Divers_OK.jpg',
    'Dons': 'http://bilingue31.free.fr/general_Dons3_OK.jpg',
    'Jardin': 'http://bilingue31.free.fr/general_Jardin_OK.jpg',
    'Papeterie': 'http://bilingue31.free.fr/general_Papeterie_OK.jpg',
    'Autre': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
  'Électronique': {
    default: 'http://bilingue31.free.fr/electro_ecouteurs2_OK.jpg',
    'Accessoires': 'http://bilingue31.free.fr/electro_Accessoires_OK.jpg',
    'Accessoires informatique': 'http://bilingue31.free.fr/electro_AccessoiresInfo_OK.jpg',
    'Appareil photo': 'http://bilingue31.free.fr/electro_AppareilPhoto2_OK.jpg',
    'Casque': 'http://bilingue31.free.fr/electro_Casque2_OK.jpg',
    'Consoles': 'http://bilingue31.free.fr/electro_Consoles2_OK.jpg',
    'Écouteurs': 'http://bilingue31.free.fr/electro_ecouteurs1_OK.jpg',
    'Électroménager': 'http://bilingue31.free.fr/electro_electromenager3_OK.jpg',
    'Enceintes': 'http://bilingue31.free.fr/electro_Enceintes_OK.jpg',
    'Image & son': 'http://bilingue31.free.fr/electro_ImageSon_OK.jpg',
    'Imprimantes': 'http://bilingue31.free.fr/electro_Imprimantes_OK.jpg',
    'Jeux vidéo': 'http://bilingue31.free.fr/electro_JeuxVideo2_OK.jpg',
    'Objets connectés': 'http://bilingue31.free.fr/electro_ObjetsConnectes1_OK.jpg',
    'Ordinateurs': 'http://bilingue31.free.fr/electro_Ordinateurs_OK.jpg',
    'Photo, audio & vidéo': 'http://bilingue31.free.fr/electro_PhotoAudioVideo1_OK.jpg',
    'Tablettes & Liseuses': 'http://bilingue31.free.fr/electro_TablettesLiseuses_OK.jpg',
    'Téléphones': 'http://bilingue31.free.fr/electro_Telephones_OK.jpg',
    'Télévision': 'http://bilingue31.free.fr/electro_Television_OK.jpg',
    'Vidéoprojecteur': 'http://bilingue31.free.fr/electro_Videoprojecteur_OK.jpg',
    'Autre': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
  'Immobilier': {
    default: 'http://bilingue31.free.fr/Immo_BureauCommerce1_OK.jpg',
    'Bureau & Commerce': 'http://bilingue31.free.fr/Immo_BureauCommerce2_OK.jpg',
    'Colocation': 'http://bilingue31.free.fr/Immo_Colocation_OK.jpg',
    'Location': 'http://bilingue31.free.fr/Immo_Location_OK.jpg',
    'Parking': 'http://bilingue31.free.fr/Immo_Parking_OK.jpg',
    'Terrain': 'http://bilingue31.free.fr/Immo_Terrain5_OK.jpg',
    'Vente': 'http://bilingue31.free.fr/Immo_Vente_OK.jpg',
    'Autre': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
  'Librairie': {
    default: 'http://bilingue31.free.fr/Libr_Librairie2_OK.jpg',
    'Bande-Dessinée': 'http://bilingue31.free.fr/Libr_BandeDessinee3_OK.jpg',
    'Biographie': 'http://bilingue31.free.fr/Libr_Biographie2_OK.jpg',
    'Conte': 'http://bilingue31.free.fr/Libr_Conte_OK.jpg',
    'Cours': 'http://bilingue31.free.fr/Libr_Cours_OK.jpg',
    'Document': 'http://bilingue31.free.fr/Libr_Document_OK.jpg',
    'Essai': 'http://bilingue31.free.fr/Libr_Essai_OK.jpg',
    'Fantasy': 'http://bilingue31.free.fr/Libr_Fantasy_OK.jpg',
    'Fantastique': 'http://bilingue31.free.fr/Libr_Fantastique_OK.jpg',
    'Géographie': 'http://bilingue31.free.fr/Libr_Geographie_OK.jpg',
    'Guide': 'http://bilingue31.free.fr/Libr_Guide_OK.jpg',
    'Histoire': 'http://bilingue31.free.fr/Libr_Histoire_OK.jpg',
    'Mémoires': 'http://bilingue31.free.fr/Libr_Memoires_OK.jpg',
    'Nouvelle': 'http://bilingue31.free.fr/Libr_Nouvelle_OK.jpg',
    'Poésie': 'http://bilingue31.free.fr/Libr_Poesie_OK.jpg',
    'Roman historique': 'http://bilingue31.free.fr/Libr_RomanHistorique_OK.jpg',
    'Roman d\'amour': 'http://bilingue31.free.fr/Libr_RomanAmour_OK.jpg',
    'Roman d\'aventures': 'http://bilingue31.free.fr/Libr_RomanAventures_OK.jpg',
    'Roman policier': 'http://bilingue31.free.fr/Libr_RomanPolicier2_OK.jpg',
    'Science-Fiction': 'http://bilingue31.free.fr/Libr_ScienceFiction_OK.jpg',
    'Théâtre': 'http://bilingue31.free.fr/Libr_Theatre_OK.jpg',
    'Autre': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
  'Loisirs': {
    default: 'http://bilingue31.free.fr/Loisirs_Loisirs_OK.jpg',
    'Antiquités': 'http://bilingue31.free.fr/Loisirs_Antiquites_OK.jpg',
    'Artistes': 'http://bilingue31.free.fr/Loisirs_Artistes_OK.jpg',
    'Billetterie': 'http://bilingue31.free.fr/Loisirs_Billetterie_OK.jpg',
    'CD - Musique': 'http://bilingue31.free.fr/Loisirs_CDMusique_OK.jpg',
    'Collection': 'http://bilingue31.free.fr/Loisirs_Collection_OK.jpg',
    'Cuisines et dînettes': 'http://bilingue31.free.fr/Loisirs_CuisinesDinettes_OK.jpg',
    'DVD - Films': 'http://bilingue31.free.fr/Loisirs_DVDFilms2_OK.jpg',
    'Instruments de musique': 'http://bilingue31.free.fr/Loisirs_InstrumentsMusique_OK.jpg',
    'Jeux & Jouets': 'http://bilingue31.free.fr/Loisirs_JeuxJouets_OK.jpg',
    'Jeux de construction': 'http://bilingue31.free.fr/Loisirs_JeuxConstruction_OK.jpg',
    'Jeux de société': 'http://bilingue31.free.fr/Loisirs_JeuxSociete_OK.jpg',
    'Jouets d’éveil': 'http://bilingue31.free.fr/Loisirs_JouetsEveil_OK.jpg',
    'Livres': 'http://bilingue31.free.fr/Loisirs_Livres_OK.jpg',
    'Loisirs créatifs': 'http://bilingue31.free.fr/Loisirs_LoisirsCreatifs_OK.jpg',
    'Modélisme': 'http://bilingue31.free.fr/Loisirs_Modelisme_OK.jpg',
    'Monnaies': 'http://bilingue31.free.fr/Loisirs_Monnaies_OK.jpg',
    'Porteurs, trotteurs et draisiennes': 'http://bilingue31.free.fr/Loisirs_PorteursTrotteursDraisiennes1_OK.jpg',
    'Poupées et accessoires': 'http://bilingue31.free.fr/Loisirs_PoupeesAccessoires_OK.jpg',
    'Puzzle': 'http://bilingue31.free.fr/Loisirs_Puzzle_OK.jpg',
    'Timbres': 'http://bilingue31.free.fr/Loisirs_Timbres_OK.jpg',
    'Vins & Gastronomie': 'http://bilingue31.free.fr/Loisirs_VinsGastronomie3_OK.jpg',
    'Voiturettes et circuits': 'http://bilingue31.free.fr/Loisirs_VoiturettesCircuits5_OK.jpg',
    'Autre': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
  'Maison': {
    default: 'http://bilingue31.free.fr/Maison_Maison_OK.jpg',
    'Armoire & placard': 'http://bilingue31.free.fr/Maison_ArmoirePlacard3_OK.jpg',
    'Buffet': 'http://bilingue31.free.fr/Maison_Buffet_OK.jpg',
    'Canapé': 'http://bilingue31.free.fr/Maison_Canape_OK.jpg',
    'Chaise, tabouret et banc': 'http://bilingue31.free.fr/Maison_ChaiseTabouretBanc1_OK.jpg',
    'Lit': 'http://bilingue31.free.fr/Maison_Lit_OK.jpg',
    'Meuble de cuisine': 'http://bilingue31.free.fr/Maison_MeubleCuisine_OK.jpg',
    'Meuble de salon': 'http://bilingue31.free.fr/Maison_MeubleSalon_OK.jpg',
    'Table': 'http://bilingue31.free.fr/Maison_Table_OK.jpg',
    'Assiette': 'http://bilingue31.free.fr/ArtTable_Assiette_OK.jpg',
    'Vaisselle': 'http://bilingue31.free.fr/ArtTable_vaisselle3_OK.jpg',
    'Verre': 'http://bilingue31.free.fr/ArtTable_Verre2_OK.jpg',
    'Horloge, pendule et réveil': 'http://bilingue31.free.fr/Deco_HorlogePenduleReveil2_OK.jpg',
    'Lampadaire': 'http://bilingue31.free.fr/Deco_Lampadaire2_OK.jpg',
    'Lampe': 'http://bilingue31.free.fr/Deco_Lampe3_OK.jpg',
    'Lustre': 'http://bilingue31.free.fr/Deco_Lustre_OK.jpg',
    'Miroir': 'http://bilingue31.free.fr/Deco_Miroir_OK.jpg',
    'Rideaux, voilage et store': 'http://bilingue31.free.fr/Deco_RideauxVoilageStore_OK.jpg',
    'Sculpture et statue': 'http://bilingue31.free.fr/Deco_SculptureStatue_OK.jpg',
    'Suspension': 'http://bilingue31.free.fr/Deco_Suspension_OK.jpg',
    'Tableau & toile': 'http://bilingue31.free.fr/Deco_TableauToile_OK.jpg',
    'Tapis': 'http://bilingue31.free.fr/Deco_Tapis_OK.jpg',
    'Vase, cache pot et céramique': 'http://bilingue31.free.fr/Deco_VaseCachePotCeramique1_OK.jpg',
    'Aspirateur': 'http://bilingue31.free.fr/ElectroMenage_Aspirateur_OK.jpg',
    'Chauffage et climatisation': 'http://bilingue31.free.fr/ElectroMenage_ChauffageClimatisation2_OK.jpg',
    'Congélateur': 'http://bilingue31.free.fr/ElectroMenage_Congelateur_OK.jpg',
    'Four': 'http://bilingue31.free.fr/ElectroMenage_Four_OK.jpg',
    'Lave-linge': 'http://bilingue31.free.fr/ElectroMenage_LaveLinge1_OK.jpg',
    'Lave-vaisselle': 'http://bilingue31.free.fr/ElectroMenage_LaveVaisselle_OK.jpg',
    'Micro-ondes': 'http://bilingue31.free.fr/ElectroMenage_MicroOndes_OK.jpg',
    'Réfrigérateur': 'http://bilingue31.free.fr/ElectroMenage_Refrigerateur_OK.jpg',
    'Déco textile': 'http://bilingue31.free.fr/Linge_DecoTextile_OK.jpg',
    'Équipement du lit': 'http://bilingue31.free.fr/Linge_EquipementLit_OK.jpg',
    'Linge de bain': 'http://bilingue31.free.fr/Linge_LingeBain_OK.jpg',
    'Linge de lit': 'http://bilingue31.free.fr/Linge_LingeLit_OK.jpg',
    'Linge de table': 'http://bilingue31.free.fr/Linge_LingeTable_OK.jpg',
    'Autre': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
  'Mode & Santé': {
    default: 'http://bilingue31.free.fr/Mode_ModeSante_OK.jpg',
    'Accessoires & Bagagerie': 'http://bilingue31.free.fr/Mode_AccessoiresBagagerie_OK.jpg',
    'Beauté, bien-être et parfums': 'http://bilingue31.free.fr/Mode_BeauteBienEtreParfums2_OK.jpg',
    'Bons Plans Mode': 'http://bilingue31.free.fr/Mode_BonsPlansMode_OK.jpg',
    'Chapeau': 'http://bilingue31.free.fr/Mode_Chapeau_OK.jpg',
    'Chaussure': 'http://bilingue31.free.fr/Mode_Chaussure3_OK.jpg',
    'Hygiène & Santé': 'http://bilingue31.free.fr/Mode_HygieneSante_OK.jpg',
    'Joaillerie': 'http://bilingue31.free.fr/Mode_Joaillerie_OK.jpg',
    'Maroquinerie': 'http://bilingue31.free.fr/Mode_Maroquinerie_OK.jpg',
    'Montre & Bijou': 'http://bilingue31.free.fr/Mode_MontreBijou_OK.jpg',
    'Vêtement': 'http://bilingue31.free.fr/Mode_Vetement1_OK.jpg',
    'Autre': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
  'Services': {
    default: 'http://bilingue31.free.fr/Service_Services_OK.jpg',
    'Baby-Sitting': 'http://bilingue31.free.fr/Service_BabySitting_OK.jpg',
    'Cours particuliers': 'http://bilingue31.free.fr/Service_CoursParticuliers_OK.jpg',
    'Entraide': 'http://bilingue31.free.fr/Service_Entraide_OK.jpg',
    'Pet': 'http://bilingue31.free.fr/Service_PetAlert2_OK.jpg',
    'Autres services': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
  'Sport & Plein air': {
    default: 'http://bilingue31.free.fr/Sport_SportPleinAir_OK.jpg',
    'Arts Martiaux': 'http://bilingue31.free.fr/Sport_ArtsMartiaux_OK.jpg',
    'Athlétisme': 'http://bilingue31.free.fr/Sport_Athletisme_OK.jpg',
    'Bateau, voile et nautisme': 'http://bilingue31.free.fr/Sport_BateauVoileNautisme_OK.jpg',
    'Fitness': 'http://bilingue31.free.fr/Sport_Fitness_OK.jpg',
    'Natation': 'http://bilingue31.free.fr/Sport_Natation_OK.jpg',
    'Pêche': 'http://bilingue31.free.fr/Sport_Peche_OK.jpg',
    'Pétanque': 'http://bilingue31.free.fr/Sport_Petanque_OK.jpg',
    'Skates, rollers, trottinettes': 'http://bilingue31.free.fr/Sport_SkatesRollersTrottinettes5_OK.jpg',
    'Sports d\'hiver': 'http://bilingue31.free.fr/Sport_SportsHiver_OK.jpg',
    'Sports de balle et ballon': 'http://bilingue31.free.fr/Sport_SportsBalleBallon_OK.jpg',
    'Vélos': 'http://bilingue31.free.fr/Sport_Velos_OK.jpg',
    'Vélo électrique': 'http://bilingue31.free.fr/Sport_VeloElectrique_OK.jpg',
    'Vélo de route': 'http://bilingue31.free.fr/Sport_VeloRoute1_OK.jpg',
    'Vélo de ville': 'http://bilingue31.free.fr/Sport_VeloVille_OK.jpg',
    'VTT': 'http://bilingue31.free.fr/Sport_VTT_OK.jpg',
    'Yoga': 'http://bilingue31.free.fr/Sport_Yoga_OK.jpg',
    'Autre': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
  'Vacances': {
    default: 'http://bilingue31.free.fr/Vacances_Vacances_OK.jpg',
    'Appartement': 'http://bilingue31.free.fr/Vacances_Appartement_OK.jpg',
    'Camping': 'http://bilingue31.free.fr/Vacances_Camping2_OK.jpg',
    'Chalet': 'http://bilingue31.free.fr/Vacances_Chalet_OK.jpg',
    'Chambre d’hôtes': 'http://bilingue31.free.fr/Vacances_ChambreHotes2_OK.jpg',
    'Maison': 'http://bilingue31.free.fr/Vacances_Maison2_OK.jpg',
    'Mobil-home': 'http://bilingue31.free.fr/Vacances_MobilHome_OK.jpg',
    'Studio': 'http://bilingue31.free.fr/Vacances_Studio_OK.jpg',
    'Villa': 'http://bilingue31.free.fr/Vacances_Villa_OK.jpg',
    'Autre': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
  'Véhicule ou Équipement': {
    default: 'http://bilingue31.free.fr/Vehicule_VehiculeEquipe_OK.jpg',
    'Camion': 'http://bilingue31.free.fr/Vehicule_Camion_OK.jpg',
    'Caravaning': 'http://bilingue31.free.fr/Vehicule_Caravaning_OK.jpg',
    'Moto': 'http://bilingue31.free.fr/Vehicule_Moto2_OK.jpg',
    'Nautisme': 'http://bilingue31.free.fr/Vehicule_Nautisme_OK.jpg',
    'Remorque': 'http://bilingue31.free.fr/Vehicule_Remorque_OK.jpg',
    'Utilitaire': 'http://bilingue31.free.fr/Vehicule_Utilitaire4_OK.jpg',
    'Vélo': 'http://bilingue31.free.fr/Vehicule_Velo2_OK.jpg',
    'Voiture': 'http://bilingue31.free.fr/Vehicule_Voiture1_OK.jpg',
    'Autre': 'http://bilingue31.free.fr/general_Autre_OK.jpg',
  },
};
